export const lyrics = [
  '♫ Never gonna',
  'give you up',
  'let you down',
  'run around',
  'and desert you',
  '♫ Never gonna',
  'make you cry',
  'say goodbye',
  'tell a lie',
  'and hurt you',
  '♫ ♪ ♫ ♪',
];

export const insults = [
  'My gran could do better',
  "And she's dead!",
  '♪ ☺',
  'What are you?',
  'An idiot sandwich?',
  '♪ ☺',
  "I wish you'd jump",
  'in the oven',
  'That would make my life',
  'A lot easier!',
  '♪ ☺',
  'Congratulations..',
  'on the worst dish',
  'in this competition',
  'so far!',
  '♪ ☺',
];
