name: Update Puzzles & README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run script:retrieve
      - run: npm run script:readme
      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "ci: :construction_worker: update puzzle list and readme" && git push
